-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('IN_REVIEW', 'APPROVED', 'REJECTED', 'PLANTING', 'COMPLETED');

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "status" "OrderStatus" NOT NULL DEFAULT 'IN_REVIEW',
ALTER COLUMN "order_date" SET DEFAULT CURRENT_TIMESTAMP;
